version: 3

sources:
  - name: week_4_hw
    database: dataengineeringzoomcamp-409819
     # For postgres:
      #database: production
    #schema: trips_data_all

      # loaded_at_field: record_loaded_at
    tables:
      - name: external_fhv
         # freshness:
           # error_after: {count: 6, period: hour}

models:
    - name: stg_fhv_tripdata
      description: >
          FHV Data
      columns:
           - name: pickup_locationid
             description: ""
           - name: dropoff_locationid
             description: ""
           - name: sr_flag,
             description: ""
           - name:  affiliated_base_number
             description: ""
           - name: dispatching_base_num
             description: ""

           - name: pickup_datetime
             description: ""
           - name: dropoff_datetime
             description: ""
